version: '3'
services:
  movie-catalog-service:
    container_name: movie-catalog-service-container
    build: ./movie-catalog-service
    ports:
      - 8081:8081
    
  movie-info-service:
    container_name: movie-info-service-container
    build: ./movie-info-service
    ports:
      - 8082:8082

  ratings-data-service:
    container_name: ratings-data-service-container
    build: ./ratings-data-service
    ports:
      - 8083:8083
  
  discovery-server:
    container_name: discovery-server-container
    build: ./discovery-server
    ports:
      - 8085:8085
    